FROM golang:1.22-alpine AS builder

WORKDIR /ascii-art-web

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o ascii-art-web

FROM alpine

WORKDIR /ascii-art-web

COPY --from=builder /ascii-art-web/ascii-art-web .
COPY --from=builder /ascii-art-web/templates ./templates
COPY --from=builder /ascii-art-web/banners ./banners

EXPOSE 8080

CMD ["./ascii-art-web"]